name = "secp256k1-db"
main = "src/index.ts"
compatibility_date = "2023-09-14"

[[kv_namespaces]]
binding = "PRIVATE_STORE"
id = "6a9b71a2c97d41fcb298a9ed9726f1f2"
preview_id = "a6327ec076ba42f589d1791afa537cf5"

