name = "secp256k1-kv-db"
type = "webpack"
account_id = "def03fa18e0fd4ec8de6d4558528abca"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
  { binding = "PRIVATE_STORE", id = "198cd439a1e2498e98c4e70f0aaaa47f", preview_id = "6bc8d50f2a904a6087a6a08f43478844" }
]
